site_name: Docs
site_url: https://docs.listrr.pro/
repo_url: https://github.com/TheUltimateC0der/listrr.pro
edit_uri: https://github.com/TheUltimateC0der/listrr.pro-docs
site_description: Documentation of all listrr.pro features and its api
plugins:
  - section-index
  - search
  - render_swagger
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  font: Open Sans
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences